redis:
  image: redis:3.0.7-alpine
scheduler:
  environment:
    REDIS_URI: redis:6379/resque
  command:
    - rake
    - resque:scheduler
  cap_drop:
    - ALL
  image: ajacques/rancher-webhook:latest
  links:
    - redis

Agent:
  environment:
    REDIS_URI: redis:6379/resque
  labels:
    io.rancher.container.pull_image: always
  image: ajacques/rancher-webhook:latest
  links:
    - redis
  cap_drop:
    - ALL

Worker:
  environment:
    QUEUE: '*'
    RANCHER_ACCESS_KEY: {access-key}
    RANCHER_SECRET_KEY: {secret-key}
    RANCHER_URI: {rancher-uri}
    REDIS_URI: redis:6379/resque
  labels:
    io.rancher.container.pull_image: always
  command:
    - rake
    - resque:work
  image: ajacques/rancher-webhook:latest
  links:
    - redis
  cap_drop:
    - ALL
